module.exports = {
  name: 'Express quotes block',
  features: [
    {
      tcid: '0',
      name: '@quotes default',
      path: '/drafts/nala/blocks/quotes/quotes-default',
      data: {
        quote1Text: 'Ladies celebrating ladies — it’s like Lilith Fair, minus the angst. Plus frittatas.',
        quote2Text: 'Every February 13th, my lady friends and I leave our husbands and our boyfriends at home, and we just come and kick it, breakfast-style.',
        quote3Text: 'I am a goddess, a glorious female warrior.',
        quote4Text: 'We have to remember what’s important in life: friends, waffles, and work. Or waffles, friends, work. But work has to come third.',
        quote5Text: 'I guess some people object to powerful depictions of awesome ladies.',
        authorSummaryText1: 'Leslie Knope,Parks and Recreation',
        authorSummaryText2: 'Leslie Knope,Parks and Recreation',
        authorSummaryText3: 'Leslie Knope,Parks and Recreation',
        authorSummaryText4: 'Leslie Knope,Parks and Recreation',
        authorSummaryText5: 'Leslie Knope,Parks and Recreation',
      },
      tags: '@quotes @quotes-default @express @smoke @regression @t1',
    },
    {
      tcid: '1',
      name: '@quotes default with photos',
      path: '/drafts/nala/blocks/quotes/quotes-default-photos',
      data: {
        quote1Text: 'I love creating flyers in Adobe Express because its intuitive interface allowed me to quickly learn and adapt, even as a newcomer."',
        quote2Text: 'Adobe Express helps me to create flyers in minutes. I love the templates and AI tools for quick-start concepts, making it easy to come up with a unique design. Going from concept to creation is fast and effortless.”',
        quote3Text: 'I love using Adobe Express to create flyers for my small business. All the tools in Adobe Express, such as the different fonts and graphics help bring my vision to life."',
        authorSummaryText1: 'Asbah WasimStudent @ University of California Berkeley',
        authorSummaryText2: 'Abs AhlijahMarketing & Content Coordinator @ Soul Session',
        authorSummaryText3: 'Erica XieOwner @ Photoshoots with Erica',
        authorImageCount: 3,
      },
      tags: '@quotes @quotes-default-photos @express @smoke @regression @t2',
    },
    {
      tcid: '2',
      name: '@quotes singular',
      path: '/drafts/nala/blocks/quotes/quotes-singular',
      data: {
        quoteText: '“I love using Adobe Express to create flyers for my small business. All the tools in Adobe Express, such as the different fonts and graphics help bring my vision to life.”',
        authorDescription: 'Erica X., Owner @ Photoshoots with Erica',
        authorImageCount: 1,
      },
      tags: '@quotes @quotes-singular @express @smoke @regression @t3',
    },
    {
      tcid: '3',
      name: '@quotes carousel',
      path: '/drafts/nala/blocks/quotes/quotes-carousel',
      data: {
        authorSummaryText1: 'Leslie Knope,Parks and Recreation',
        authorSummaryText2: 'Leslie Knope,Parks and Recreation',
        authorSummaryText3: 'Leslie Knope,Parks and Recreation',
        authorSummaryText4: 'Leslie Knope,Parks and Recreation',
        authorSummaryText5: 'Leslie Knope,Parks and Recreation',
        quote1Text: 'Ladies celebrating ladies — it’s like Lilith Fair, minus the angst. Plus frittatas.',
        quote2Text: 'Every February 13th, my lady friends and I leave our husbands and our boyfriends at home, and we just come and kick it, breakfast-style.',
        quote3Text: 'I am a goddess, a glorious female warrior.',
        quote4Text: 'We have to remember what’s important in life: friends, waffles, and work. Or waffles, friends, work. But work has to come third.',
        quote5Text: 'I guess some people object to powerful depictions of awesome ladies.',
        authorImageCount: 5,
      },
      tags: '@quotes @quotes-carousel @express @smoke @regression @t4',
    },
  ],
};
