name: Merge to stage

on:
  schedule:
    - cron: '0 */4 * * *' # Run every 4 hours
  workflow_dispatch: # Allow manual trigger
  repository_dispatch:
    types: [merge-to-stage]

env:
  REQUIRED_APPROVALS: ${{ secrets.REQUIRED_APPROVALS }}
  MAX_PRS_PER_BATCH: ${{ secrets.MAX_PRS_PER_BATCH }}
  STAGE_RCP_OFFSET_DAYS: ${{ secrets.STAGE_RCP_OFFSET_DAYS }}

jobs:
  merge-to-stage:
    runs-on: ubuntu-latest
    environment: express_pr_merge

    steps:
      - uses: actions/create-github-app-token@v1
        id: express-merge-token
        with:
          app-id: ${{ secrets.EXPRESS_MERGE_APP_ID }}
          private-key: ${{ secrets.EXPRESS_MERGE_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge to stage or queue to merge
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.express-merge-token.outputs.token }}
          script: |
            const main = require('./.github/workflows/merge-to-stage.js')
            main({ github, context }) 
