name: QA Label Management

on:
  pull_request:
    types: [opened, edited, ready_for_review, converted_to_draft, labeled, unlabeled, submitted, synchronize, reopened]

jobs:
  manage-labels:
    name: Manage All PR Labels
    runs-on: ubuntu-latest
    steps:
      - name: Manage labels based on PR state and approvals
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            
            console.log(`Workflow triggered for PR #${number}, action: ${context.payload.action}`);
            
            // Get PR details
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number
            });
            
            const currentLabels = pr.data.labels.map(label => label.name);
            const isDraft = pr.data.draft;
            const isTestMode = currentLabels.includes('test-qa-workflow');
            
            console.log(`Current labels on PR #${number}:`, currentLabels);
            console.log(`Is draft: ${isDraft}, Is test mode: ${isTestMode}`);
            
            // Start fresh - only keep non-Ready labels
            const targetLabels = currentLabels.filter(label => 
              !['Ready for Review', 'Ready for review', 'Ready for QA', 'Ready for qa'].includes(label)
            );
            
            // Add the correct Ready label based on state
            if (isDraft) {
              // Draft PRs should have no Ready labels
              console.log(`Draft PR - no Ready labels needed`);
            } else if (isTestMode || (await checkApprovals(owner, repo, number)) >= 2) {
              // Ready for QA - 2+ approvals and no request changes
              targetLabels.push('Ready for QA');
              console.log(`Adding Ready for QA label`);
            } else {
              // Ready for Review - default for non-draft PRs
              targetLabels.push('Ready for Review');
              console.log(`Adding Ready for Review label`);
            }
            
            // Check if labels actually changed to avoid unnecessary operations
            const currentReadyLabels = currentLabels.filter(label => 
              label.includes('Ready for')
            );
            const targetReadyLabels = targetLabels.filter(label => 
              label.includes('Ready for')
            );
            
            const labelsChanged = JSON.stringify(currentReadyLabels.sort()) !== JSON.stringify(targetReadyLabels.sort());
            
            if (labelsChanged) {
              console.log(`Labels changed: ${currentReadyLabels.join(', ')} → ${targetReadyLabels.join(', ')}`);
              
              // Set the exact label list
              await github.rest.issues.setLabels({
                owner,
                repo,
                issue_number: number,
                labels: targetLabels
              });
              console.log(`Set labels to: ${targetLabels.join(', ')}`);
            } else {
              console.log(`No label changes needed - Ready labels already correct`);
            }
            
            // Helper function to check approvals
            async function checkApprovals(owner, repo, number) {
              const reviews = await github.rest.pulls.listReviews({
                owner,
                repo,
                pull_number: number
              });
              
              let approvalCount = 0;
              for (const review of reviews.data) {
                if (review.state === 'APPROVED') {
                  approvalCount++;
                } else if (review.state === 'CHANGES_REQUESTED') {
                  return 0; // Request changes blocks QA
                }
              }
              return approvalCount;
            }
