name: Nala Tests Label Trigger

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened, ready_for_review, converted_to_draft ]

jobs:
  manage-ready-for-review-label:
    name: Manage Ready for Review Label
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' && (
        github.event.action == 'opened' ||
        github.event.action == 'ready_for_review' ||
        github.event.action == 'converted_to_draft'
      )
    steps:
      - name: Add Ready for review label (non-draft PRs)
        if: github.event.pull_request.draft == false
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            
            // Add the "Ready for review" label
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: number,
              labels: ['Ready for review']
            });
            
            console.log(`Added "Ready for review" label to PR #${number}`);

      - name: Remove Ready for review label (draft PRs)
        if: github.event.pull_request.draft == true
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            
            // Remove the "Ready for review" label
            await github.rest.issues.removeLabel({
              owner,
              repo,
              issue_number: number,
              name: 'Ready for review'
            });
            
            console.log(`Removed "Ready for review" label from PR #${number}`);

  action:
    name: Running Nala E2E UI Tests
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(join(github.event.pull_request.labels.*.name, ' '), 'run-nala')

    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set execute permission for nalarun.sh
        run: chmod +x ./nala/utils/pr.run.sh

      - name: Run Nala Tests via pr.run.sh
        run: ./nala/utils/pr.run.sh
        env:
          labels: ${{ join(github.event.pull_request.labels.*.name, ' ') }}
          branch: ${{ github.event.pull_request.head.ref }}
          repoName: ${{ github.repository }}
          prUrl: ${{ github.event.pull_request.head.repo.html_url }}
          prOrg: ${{ github.event.pull_request.head.repo.owner.login }}
          prRepo: ${{ github.event.pull_request.head.repo.name }}
          prBranch: ${{ github.event.pull_request.head.ref }}
          prBaseBranch: ${{ github.event.pull_request.base.ref }}
          GITHUB_ACTION_PATH: ${{ github.workspace }}
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}

