name: Simple Release Notification

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '*.md'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL || '#express-releases' }}

jobs:
  notify-release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'adobecom' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract PR information
        id: extract-prs
        run: |
          # Get recent merge commits
          MERGE_COMMITS=$(git log --oneline -10 --grep="Merge pull request")
          
          if [ -n "$MERGE_COMMITS" ]; then
            # Extract PR titles and numbers
            PR_LIST=""
            while IFS= read -r line; do
              if echo "$line" | grep -q "Merge pull request"; then
                # Extract PR number
                PR_NUM=$(echo "$line" | grep -o '#[0-9]*')
                
                # Extract PR title (everything after "Merge pull request #XXX: ")
                PR_TITLE=$(echo "$line" | sed 's/.*Merge pull request #[0-9]*: //' | sed 's/ from.*//')
                
                if [ -n "$PR_NUM" ] && [ -n "$PR_TITLE" ]; then
                  PR_LIST="${PR_LIST}- ${PR_TITLE} ${PR_NUM}\n"
                fi
              fi
            done <<< "$MERGE_COMMITS"
            
            echo "pr_list<<EOF" >> $GITHUB_OUTPUT
            echo -e "$PR_LIST" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "pr_list=No recent PRs found" >> $GITHUB_OUTPUT
          fi

      - name: Send release notification
        if: env.SLACK_WEBHOOK_URL != '' && steps.extract-prs.outputs.pr_list != ''
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          channel: ${{ env.SLACK_CHANNEL }}
          webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
          custom_payload: |
            {
              "text": "🚀 *Express Milo Release Deployed*",
              "attachments": [
                {
                  "color": "good",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                      "short": true
                    }
                  ]
                },
                {
                  "color": "#36a64f",
                  "text": "## Changes in this Release\n${{ steps.extract-prs.outputs.pr_list }}",
                  "mrkdwn_in": ["text"]
                }
              ],
              "footer": "Express Milo",
              "footer_icon": "https://github.com/adobecom/express-milo/raw/main/express/code/img/favicon.ico"
            }

      - name: Fallback notification
        if: failure() && env.SLACK_WEBHOOK_URL != ''
        run: |
          echo "❌ Release notification failed"
          echo "Commit: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
